add _cached_sleep attribute to __init__
adafruit/Adafruit_CircuitPython_SHTC3 pull request #19
Opened 2022-10-18 16:15 UTC by tcfranks

resolves #18 
submitted for review / comment

2022-10-18 18:03 UTC, tekktrik requested changes

2022-10-18 18:03 UTC, tekktrik commented on adafruit_shtc3.py
> +        self._cached_sleep = False
I would change this to use the setter so it does the I2C stuff as well:

```suggestion
        self.sleeping = False
```

2022-10-25 18:30 UTC, tcfranks commented
I'm willing to close the pr, based on feedback, as rejected, withdrawn, whatever.

I've attached the code.py I was simulating with, and on a pico, under both 7.3.3 and 8.00 B2 I got errors as follows:
code.py output:
]0;🐍code.py | 8.0.0-beta.2\in sleeping setter
sleep_enabled = False
Traceback (most recent call last):
  File "code.py", line 221, in <module>
  File "code.py", line 75, in __init__
  File "code.py", line 122, in sleeping
AttributeError: 'SHTC3' object has no attribute '_cached_sleep'
]0;🐍122@code.py AttributeError | 8.0.0-beta.2\
Code done running.

Also, I would point out that the Sensirion SHTC3 datasheet says that "Upon VDD reaching the power-up voltage level VPOR, the SHTC3 enters the idle state after a duration of tPU. After that,
the sensor should be set to sleep mode with the command given in Table 9".  According to the way the class is organized, we should be setting the sleep function to true in the init.  Otherwise it will remain 'not in sleep mode' until the first measurement is taken, at which time on exit it will be set to sleep.

still happy to forget the whole thing though....

1
[sim code.zip](https://github.com/adafruit/Adafruit_CircuitPython_SHTC3/files/9862978/sim.code.zip)

2022-10-29 14:11 UTC, closed without merging

2022-10-29 14:12 UTC, tcfranks commented
closed as CNR (see discussion)